### ISSUE TITLE
Navbar tabs moving aside on hovering

### ISSUE THREAD

**Issue by digambar-t7** [yessGlory17/nft-marketplace#17]
The tabs on the navbar move a bit aside when the user hovers over it.
I can fix this.

**Comment by yessGlory17** [comment]
Katkılarınızı sabırsızlıkla bekliyorum. Projeyi geniş kitlelere tanıtmamıza, hatayı düzeltmemize ve özellikler eklememize yardımcı olursanız çok mutlu oluruz.

**Comment by yessGlory17** [comment]
It is very important that our project collects 100 stars to be announced to the public. This is an important threshold for us.

**Comment by digambar-t7** [comment]
As the quality of the project will improve, stars will increase.
So we must focus only on building a better project

**Comment by yessGlory17** [comment]
I totally agree with what you said. And I believe we will achieve it.

**Comment by yessGlory17** [comment]
Excellent. Thank you very much. Send PR.
@digambar-t7

**Comment by yessGlory17** [comment]
@all-contributors please add @digambar-t7 for bug .
