### ISSUE TITLE
Website showing only black screen when running 'npm start'

### ISSUE THREAD

**Issue by gaurav24072002** [yessGlory17/nft-marketplace#45]
**Describe the bug**
When running ```npm start``` the react app opens but with only black screen and no components and features.

**Expected behavior**
The react app should open the home page with all components like header etc.

**Screenshots**
![ss](https://user-images.githubusercontent.com/77109758/167711631-1d3772b2-c227-425c-ae98-334766010b5b.PNG)

**Comment by yessGlory17** [comment]
Thank you for the information. I solved the error you told. You must follow the steps below.

### Clone Project

SSH CLONE
`git clone git@github.com:yessGlory17/nft-marketplace.git`


HTTPS CLONE
`git clone https://github.com/yessGlory17/nft-marketplace.git`


### INSTALL DEPENDENCIES

`npm install`

### START PROJECT

`npm start`

![image](https://user-images.githubusercontent.com/52113663/167738991-e40c8fcd-1a94-4ce3-96cc-6fc3c6b9765e.png)


Now everything is ready. You can go to the url below.


![image](https://user-images.githubusercontent.com/52113663/167739168-2cf3fce7-1d76-454b-92e8-d8fff943dce3.png)
