### ISSUE TITLE
Create Contribution Guideline

### ISSUE THREAD

**Issue by yessGlory17** [yessGlory17/nft-marketplace#7]

**Comment by GehadSalemFekry** [comment]
I created a contribution guide here and would like to hear your feedback.
https://github.com/GehadSalemFekry/nft-marketplace/blob/main/CONTRIBUTING.md

**Comment by yessGlory17** [comment]
Excellent. Thank you very much. Send PR.

**Comment by yessGlory17** [comment]
@all-contributors please add @GehadSalemFekry  for Contribution Guide.

**Comment by yessGlory17** [comment]
@all-contributors please add @GehadSalemFekry  for content .
